_BASE_: "../Base-BlendMask.yaml"
MODEL:
  RESNETS:
    OUT_FEATURES: ["res2", "res3", "res4", "res5"]
  FPN:
    IN_FEATURES: ["res2", "res3", "res4", "res5"]
  SEM_SEG_HEAD:
    LOSS_WEIGHT: 0.5
  PANOPTIC_FPN:
    COMBINE:
      ENABLED: True
      INSTANCES_CONFIDENCE_THRESH: 0.45
      OVERLAP_THRESH: 0.4
DATASETS:
  TRAIN: ("coco_tooth_train",)
  TEST: ("coco_tooth_val",)
