_BASE_: "Base-BlendMask.yaml"
MODEL:
  WEIGHTS: 'D:\project_seg\AdelaiDet\R_101_dcni3_5x.pth'
  RESNETS:
    DEPTH: 101
    DEFORM_ON_PER_STAGE: [False, True, True, True]
    DEFORM_MODULATED: True
    DEFORM_INTERVAL: 3
SOLVER:
  STEPS: (6000, 10000)
  MAX_ITER: 11000
INPUT:
  MIN_SIZE_TRAIN: (640, 864)
  MIN_SIZE_TRAIN_SAMPLING: "range"
  MAX_SIZE_TRAIN: 1440
  CROP:
    ENABLED: True
TEST:
  EVAL_PERIOD: 15000
OUTPUT_DIR: "outputs/test5"
