_BASE_: "Base-BlendMask.yaml"
MODEL:
  WEIGHTS: "detectron2://ImageNetPretrained/MSRA/R-101.pkl"
  RESNETS:
    DEPTH: 101
SOLVER:
  STEPS: (16000, 180000)
  MAX_ITER: 20000
OUTPUT_DIR: "output/blendmask/R_101_3x"
