MODEL:
  META_ARCHITECTURE: "SOLOv2"
  MASK_ON: True
  BACKBONE:
    NAME: "build_resnet_fpn_backbone"
  RESNETS:
    OUT_FEATURES: ["res2", "res3", "res4", "res5"]
  FPN:
    IN_FEATURES: ["res2", "res3", "res4", "res5"]
DATASETS:
  TRAIN: ("coco_tooth_train",)
  TEST: ("coco_tooth_val",)
SOLVER:
  IMS_PER_BATCH: 4
  BASE_LR: 0.1
  WARMUP_FACTOR: 0.01
  WARMUP_ITERS: 11000
  STEPS: (3000, 11000)
  MAX_ITER: 12000
INPUT:
  MIN_SIZE_TRAIN: (640, 672, 704, 736, 768, 800)
  MASK_FORMAT: "bitmask"
VERSION: 2


